# Generated by Django 3.2.7 on 2021-11-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/img', verbose_name='Картинки'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
